### ISSUE TITLE
Syntax on DECLARE

### ISSUE THREAD

**Issue by NielsNAK** [ben-taylor-ps/acnu#1]
Hi Ben,

Actually the DECLARE is define like this : 
"DECLARE ${1|GLOBAL, MGLOBAL, CGLOBAL|}${2|NOREC, NOSHOW, SPIED|}${3|DEF=, |}"
I guess it's better to put some space on argument like this : 
"DECLARE ${1|GLOBAL, MGLOBAL, CGLOBAL|} ${2|NOREC, NOSHOW, SPIED|} ${3|DEF=, |}"

Best Regards
Niels AKKAL

**Comment by ben-taylor-ps** [comment]
Hi Niels, it should be fixed now.

I also changed the way the declare snippet works, 

there's declarefull which includes every possible option for a declare

declareglobal which declares a standard global variable, none of the trigw, trigr etc

declarelocal for declaration inside a macro, no global keyword.
