### ISSUE TITLE
TAB in template and ${2:Name} for "MACRO"

### ISSUE THREAD

**Issue by NielsNAK** [ben-taylor-ps/acnu#2]
Hi Ben,

I have modify the macro template I added a space before " # ", It's better to wide the macro :
	"acnu-macro":
	{
	   "prefix": "Macro",
	   "body": [
		   "#----------------------------------------------------------------#",
		   "Macro=${TM_SELECTED_TEXT:${1:MyCode}}()${2|\\,OVERW,\\,FAST,\\,DEBUG,\\,GENERIC_ARGS|}",
		   " # Begin of Specific MACRO - ${1}",
		   " # Macro creation by Niels AKKAL - $CURRENT_DATE $CURRENT_MONTH_NAME_SHORT $CURRENT_YEAR ==>",
		   " # Macro review   by XX XXX XXXX",
		   " \n${0:\n}\n",
		   " # End of Specific MACRO - ${1}",
		   "EndMacro",
		   "#----------------------------------------------------------------#"
	   ],
	   "description": "Creation of a macro"
	},

![Macro hide](https://github.com/ben-taylor-ps/acnu/assets/154224543/6e0067f8-2036-4db3-b460-061ef41bc7a3)

On line a " # Macro creation by ${2:Name} $CURRENT_DATE $CURRENT_MONTH_NAME_SHORT $CURRENT_YEAR ==>",
 ${2:Name} is refer to this arguement :  ${2|\\,OVERW,\\,FAST,\\,DEBUG,\\,GENERIC_ARGS|
so we have this when we create macro : 
![image](https://github.com/ben-taylor-ps/acnu/assets/154224543/0e5ecec9-e132-49d6-933c-4355a35e3301)

Thanks for your Work, It's very useful!
Best regards
Niels AKKAL

**Comment by ben-taylor-ps** [comment]
Hi Niels,

I have added tab before the #, I think this will take into account the settings that people have for their spacing in VSCode. I have also fixed the error with macro creation where it would take the parameters at the end of the macro as the name.

Thank you 

Ben
